## WAP to add two matrix.

### Using for loop

In [5]:
X = [[1,2,3],
    [2,5,6],
     [5,6,7]]
y = [[3,5,6],
     [2,6,9],
     [3,6,8]]
r= [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]

for i in range(len(X)):
    for j in range(len(X[0])):
        r[i][j] = X[i][j]+y[i][j]

for i in r:
    print(i)

[4, 7, 9]
[4, 11, 15]
[8, 12, 15]


### Using numPy 

In [8]:
import numpy as np
X = np.array(X)
y = np.array(y)

print(X+y)

[[ 4  7  9]
 [ 4 11 15]
 [ 8 12 15]]
